### PR TITLE
fix/glob-loaders-lookup-node modules

### LINKED ISSUE #1285: New glob loaders find resources outside of eventcatalog
### I tried this:

After updating from 2.29.4 to 2.30.7 we noticed a strange error when building the catalog.

### This happened:

When running `npm run build` we received the following error:
```
10:03:32 [ERROR] [vite] ✗ Build failed in 6.01s
[@mdx-js/rollup] Expected a closing tag for `<url>` (23:30-23:35) before the end of `paragraph`
file: .../eventcatalog/custom-generator/node_modules/source-map-url/changelog.mdx:23:9
```

While its not clear to me what exactly the error is, the changelog.md(x) file mentioned does exist but is something outside of our eventcatalog.

### I expected this:

It should not look for files outside the scope of eventcatalog.

### Is there a workaround?

_No response_

### Anything else?

_No response_

### EventCatalog Version

2.30.7

### Node.js Version

22

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by carlosallexandre**
## Motivation

Glob patterns without a base path (e.g., `**/changelog.(md|mdx)`) cause the Astro loader to search inside `node_modules/`, as noted by @otbe in #1285.
This PR updates the glob patterns to explicitly exclude `node_modules`.

## Related Issue
- Closes #1285

### CODE REVIEW

File: scripts/build-ci.js [hunk 1]
```diff
@@ -27,4 +27,9 @@ execSync(`cross-env NODE_ENV=CI PROJECT_DIR=${projectDIR} CATALOG_DIR=${catalogD
 // Type check
 execSync(`pnpm exec astro check --minimumSeverity error --root ${catalogDir}`, {
   stdio: 'inherit',
+  env: {
+    ...process.env,
```
Comment (boyney123) [inline scripts/build-ci.js:31]: Hey!

Just wondering why we need to pass the env now?

**Comment by boyney123** [comment]
Nice find! thanks @carlosallexandre !

File: scripts/build-ci.js (hunk 1 above)
Comment (carlosallexandre) [reply scripts/build-ci.js:31]: To fix that https://github.com/event-catalog/eventcatalog/pull/1169#issuecomment-2696837538

Comment (boyney123) [reply scripts/build-ci.js]: I removed the spread of process, let's how that goes, and be more explicit if we want to pass it certain things
